# Driver JDBC SQLite
datasource.driver=org.sqlite.JDBC

# Opción recomendada: BD fuera de resources (para que sea "escribible")
# Se crea automáticamente al ejecutar schema.sql
datasource.url=jdbc:sqlite:target/centro_deportivo.db